[workspace]
resolver = "2"
members = [
    "packages/prepare",
]

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
#dioxus = { git = "https://github.com/DioxusLabs/dioxus.git", rev = "40df088b7dd355c781b827df17d36b2ec40b3469" }
dioxus = "0.5.1"
