[workspace]
resolver = "2"
members = [
    "packages/engine",
    "packages/web",
]

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
dioxus = "0.5"
pob-engine = { path = "packages/engine" }
pob-web = { path = "packages/web" }
