[config]
default_to_workspace = false

[tasks.build]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-emscripten", "-p", "pob-engine", "--release"]
env = { "EMCC_CFLAGS" = "-O3" }

[tasks.copy-engine]
script_runner = "@duckscript"
script = '''
mkdir packages/web/dist
glob_cp target/pob_engine.* packages/web/dist/
cd vendor/PathOfBuilding/src
glob_cp ./**/*.png ../../../packages/web/dist/
glob_cp ./**/*.jpg ../../../packages/web/dist/
'''

[tasks.watch-build]
dependencies = ["build", "copy-engine"]
watch = true

[tasks.serve-web]
command = "dx"
args = ["serve", "--bin", "pob-web"]

[tasks.serve]
run_task = { name = ["serve-web", "watch-build"], fork = true, parallel = true }
