[config]
default_to_workspace = false

[tasks.build]
command = "cargo"
args = ["build", "--target", "wasm32-unknown-emscripten", "-p", "pob-engine"]

[tasks.copy-engine]
script_runner = "@duckscript"
script = '''
mkdir packages/web/dist
cp target/pob_engine.mjs packages/web/dist/pob_engine.mjs
cp target/pob_engine.wasm packages/web/dist/pob_engine.wasm
'''

[tasks.watch-build]
dependencies = ["build", "copy-engine"]
watch = true

[tasks.serve-web]
command = "dx"
args = ["serve", "--bin", "pob-web"]

[tasks.serve]
run_task = { name = ["serve-web", "watch-build"], fork = true, parallel = true }
