[package]
name = "pob-web"
version = { workspace = true }
edition = "2021"
publish = false

[dependencies]
dioxus = { workspace = true, features = ["web"] }
wasm-bindgen = "0.2"
tracing = "0.1"
tracing-wasm = "0.2"
