[package]
name = "pob-web"
version = { workspace = true }
edition = "2021"
publish = false

[dependencies]
dioxus = { workspace = true, features = ["web"] }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Document", "Element", "HtmlCanvasElement", "HtmlElement", "Node", "Window"] }
futures-util = "0.3"
tracing = "0.1"
tracing-wasm = "0.2"
