[package]
name = "pob-engine"
version = { workspace = true }
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.9", features = ["lua52", "vendored"] }
tracing = "0.1"
